import { cookies } from "next/headers";
import "./globals.css";
import { ThemeName, getTheme } from "../../styled-system/themes";
import { Metadata } from "next";
import { css } from "../../styled-system/css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const store = await cookies();
  const themeName = (store.get("theme")?.value as ThemeName) ?? "light";
  const theme = themeName && (await getTheme(themeName));

  return (
    <html
      lang="en"
      data-panda-theme={themeName ? themeName : undefined}
      className={css({
        fontFamily: "Cormorant Garamond",
        bg: "body",
        color: "text",
      })}
    >
      {themeName && (
        <head>
          <style
            type="text/css"
            id={theme.id}
            dangerouslySetInnerHTML={{ __html: theme.css }}
          />
        </head>
      )}
      <body>{children}</body>
    </html>
  );
}
