import type { Metadata } from "next";
import "./globals.css";
import { css } from "../../styled-system/css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={css({ fontFamily: "Cormorant Garamond" })}>
      <body>{children}</body>
    </html>
  );
}
